log:
  level: debug
deployers:
  python:
    deployer_id: python
    modulePullPolicy: IfNotPresent
    pythonPath: /home/mleader/.pyenv/versions/3.9.18/bin/python
    workdir: /home/mleader/workspace/arcalot/arcaflow/arcaflow_test_workflows/python_deployer_wait_simple/tmp
logged_outputs:
  error:
    level: error
  #success:
  #  level: info
